name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  grafana-dash:
    runs-on: ubuntu-latest  # Added the missing runs-on key
    steps:
      - name: Install Grafana Alloy
        run: |
          /bin/sh -c "$(curl -fsSL https://storage.googleapis.com/cloud-onboarding/alloy/scripts/install-linux.sh)"
        env:
          GCLOUD_HOSTED_METRICS_ID: "2676831"
          GCLOUD_HOSTED_METRICS_URL: "https://prometheus-prod-43-prod-ap-south-1.grafana.net/api/prom/push"
          GCLOUD_HOSTED_LOGS_ID: "1334092"
          GCLOUD_HOSTED_LOGS_URL: "https://logs-prod-028.grafana.net/loki/api/v1/push"
          GCLOUD_FM_URL: "https://fleet-management-prod-018.grafana.net"
          GCLOUD_FM_POLL_FREQUENCY: "60s"
          GCLOUD_FM_HOSTED_ID: "1376298"
          ARCH: "amd64"
          GCLOUD_RW_API_KEY: ${{ secrets.GRAFANA_API_KEY }}  # Securely referenced

  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/quickrate:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/quickrate:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
